### ISSUE TITLE
ZV vizitka

### ISSUE THREAD

**Issue by IxAriela** [saurinne/Koderka_u2_vizitka#1]
Ahoj,

vypadá to dobře, technicky tam nemáš ani žádnou chybu :)

Ale pokud bys dostala zadání od zákazníka, tak je tam pár drobností, na které si dát pozor :)

- font-family, pokud je použitý na celé stránce jako tady, je lepší dávat přímo na body :)
- z nějakého důvodu se mi na pages nezobrazuje stín na main (ani v css), ale tady v kodu ho vidím, tak těžko říct, proč se tam nepropsal. Ale i tak, stín funguje tak, že ho většinou rozmažeš a tím se zesvětlí jeho barva. Takže dát mu barvu rgba(0,0,0,0.1), tedy téměř průhlednou, nedává smysl, nepůjde vůbec vidět.
- obrázek v rohu nemá stín, ale v návrhu je (hodně jemný, ale je)
- 30px má být mezera mezi druhým odstavcem a tlačítky, ale mezi odstavci by mělo být trošku méně (občas jsem si otevřela obrázek v gimpu/photoshopu a prostě měřila vzdálenosti) :)

Nic z toho nemusíš opravovat. Až si to přečteš, tak to prosím uzavři :)

**Comment by saurinne** [comment]
Ahoj, děkuju, budu an to myslet.
